/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.model.LoginUser;
import hotel.service.HotelService;

/**
 *
 * @author ferha
 */
public class MainFrame extends javax.swing.JFrame {

    private HotelService hotelService;
    private LoginUser user;
    private LoginFrame username;
    

    /**
     * Creates new form HomeFrame
     */
    public MainFrame() {
        initComponents();
    }

    public MainFrame(HotelService hotelService) {
        initComponents();
        this.hotelService = hotelService;
    }

    public MainFrame(HotelService hotelService, LoginUser user) {
        initComponents();
        this.hotelService = hotelService;
        this.user = user;
        jLabel6.setText(user.getName() + " " + user.getSurname());
        grantUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        roomDataBtn = new javax.swing.JButton();
        registerDataBtn = new javax.swing.JButton();
        customerDataBtn = new javax.swing.JButton();
        paymentDataBtn = new javax.swing.JButton();
        workerDataBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel4.setText("profiles");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roomDataBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\bed (1).png")); // NOI18N
        roomDataBtn.setBorder(null);
        roomDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomDataBtnActionPerformed(evt);
            }
        });

        registerDataBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\group (1).png")); // NOI18N
        registerDataBtn.setBorder(null);
        registerDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDataBtnActionPerformed(evt);
            }
        });

        customerDataBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\online-booking.png")); // NOI18N
        customerDataBtn.setBorder(null);
        customerDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDataBtnActionPerformed(evt);
            }
        });

        paymentDataBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\money-bag.png")); // NOI18N
        paymentDataBtn.setBorder(null);
        paymentDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDataBtnActionPerformed(evt);
            }
        });

        workerDataBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\service.png")); // NOI18N
        workerDataBtn.setBorder(null);
        workerDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerDataBtnActionPerformed(evt);
            }
        });

        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\logout (2).png")); // NOI18N
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(registerDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workerDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(customerDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(registerDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(workerDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferha\\Downloads\\boy (1).png")); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel5.setText("Welcome,");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(190, 190, 190)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workerDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerDataBtnActionPerformed
        WorkerFrame wf = new WorkerFrame(hotelService);
        wf.setVisible(true);
        MainFrame mainFrame = new MainFrame(hotelService);
        mainFrame.setVisible(false);
        this.dispose();       
    }//GEN-LAST:event_workerDataBtnActionPerformed

    private void registerDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDataBtnActionPerformed
        RegisterFrame rf = new RegisterFrame(hotelService);
        rf.setVisible(true);
        MainFrame mainFrame = new MainFrame(hotelService);
        mainFrame.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_registerDataBtnActionPerformed

    private void roomDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomDataBtnActionPerformed
        RoomFrame rFrame = new RoomFrame(hotelService);
        rFrame.setVisible(true);
        MainFrame mainFrame = new MainFrame(hotelService);
        mainFrame.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_roomDataBtnActionPerformed

    private void customerDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDataBtnActionPerformed
        CustomerFrame cf = new CustomerFrame(hotelService);
        cf.setVisible(true);
        MainFrame mainFrame = new MainFrame(hotelService);
        mainFrame.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_customerDataBtnActionPerformed

    private void paymentDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDataBtnActionPerformed
        PaymentFrame pf = new PaymentFrame(hotelService);
        pf.setVisible(true);
     //   MainFrame mainFrame = new MainFrame(hotelService);
     //   mainFrame.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_paymentDataBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginFrame loginFrame = new LoginFrame(hotelService);
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerDataBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton paymentDataBtn;
    private javax.swing.JButton registerDataBtn;
    private javax.swing.JButton roomDataBtn;
    private javax.swing.JButton workerDataBtn;
    // End of variables declaration//GEN-END:variables
    
    private void grantUser() {
        String role = user.getRole().getRoleName();
        if (role.equalsIgnoreCase("ROLE REGISTER")) {
            paymentDataBtn.setVisible(false);
        } else if (role.equalsIgnoreCase("ROLE_WORKER")) {
            paymentDataBtn.setVisible(false);
        }
    }

}
