/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.model.Item;
import hotel.model.Payment;
import hotel.model.Register;
import hotel.model.Room;
import hotel.model.Worker;
import hotel.service.HotelService;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ferha
 */
public class NewPaymentFrame extends javax.swing.JFrame {

    private HotelService hotelService;

    /**
     * Creates new form NewPaymentFrame
     */
    public NewPaymentFrame() {
        initComponents();
    }

    public NewPaymentFrame(HotelService hotelService) {
        initComponents();
        this.hotelService = hotelService;
        showWorkerCombo();
        showRegisterCombo();
        showRoomCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerCmb = new javax.swing.JComboBox<>();
        workerCmb = new javax.swing.JComboBox<>();
        roomCmb = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        payDate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        registerCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCmbActionPerformed(evt);
            }
        });

        workerCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        workerCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerCmbActionPerformed(evt);
            }
        });

        jLabel1.setText("Register");

        jLabel2.setText("Worker");

        jLabel3.setText("Room");

        jLabel4.setText("Amount");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("AZN");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        payDate.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workerCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workerCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            Item registerItem = (Item) registerCmb.getSelectedItem();
            Item workItem = (Item) workerCmb.getSelectedItem();
            Item roomItem = (Item) roomCmb.getSelectedItem();
            if(workItem.getId() == 0){
                JOptionPane.showMessageDialog(null, "Please select worker!", "Warning", JOptionPane.ERROR_MESSAGE);
            }else if(registerItem.getId() == 0){
                JOptionPane.showMessageDialog(null, "Please select register!", "Warning", JOptionPane.ERROR_MESSAGE);
            }else if(roomItem.getId() == 0){
                JOptionPane.showMessageDialog(null, "Please select room!", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{    
            Float amount = Float.valueOf(jTextField1.getText());
            Date payDate = jDateChooser1.getDate();
            Payment payment = new Payment();
            Register register = new Register();
            Worker worker = new Worker();
            Room room = new Room();
            register.setId(registerItem.getId());
            worker.setId(roomItem.getId());
            room.setId(roomItem.getId());
            payment.setRegister(register);
            payment.setWorker(worker);
            payment.setRoom(room);
            payment.setAmount(amount);
            payment.setPayDate(payDate);
            boolean isAdded = hotelService.addPayment(payment);
            if (isAdded) {
                JOptionPane.showMessageDialog(null, "Payment has been succesfully added!","Success",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Problem! Payment has not  been succesfully added!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Problem! Payment has not been succesfully added!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void registerCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerCmbActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void workerCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workerCmbActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel payDate;
    private javax.swing.JComboBox<String> registerCmb;
    private javax.swing.JComboBox<String> roomCmb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> workerCmb;
    // End of variables declaration//GEN-END:variables

    private void showWorkerCombo() {
        try {
            DefaultComboBoxModel workerCombo = new DefaultComboBoxModel();
            workerCmb.setModel(workerCombo);
            workerCombo.addElement(new Item((long)0, "Select worker!"));
            List<Worker> workerList = hotelService.getWorkerList();
            for (Worker worker : workerList) {
                workerCombo.addElement(new Item(worker.getId(), worker.getName() + " " + worker.getSurname()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showRegisterCombo() {
        try {
            DefaultComboBoxModel registerCombo = new DefaultComboBoxModel();
            registerCmb.setModel(registerCombo);
            registerCombo.addElement(new Item((long)0,"Select register!"));
            List<Register> registerList = hotelService.getRegisterList();
            for (Register register : registerList) {
                registerCombo.addElement(new Item(register.getId(), register.getName() + " " + register.getSurname()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showRoomCombo() {
        try {
            DefaultComboBoxModel roomCombo = new DefaultComboBoxModel();
            roomCmb.setModel(roomCombo);
            roomCombo.addElement(new Item((long)0, "Select room!"));
            List<Room> roomList = hotelService.getRoomList();
            for (Room room : roomList) {
                roomCombo.addElement(new Item(room.getId(), room.getRoomNumber()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
